// SPDX-License-Identifier: Apache-2.0

//! Module for representing Substrait protobuf input.
//!
//! The structures here are generated using [`prost`], but have a bunch of
//! extra traits from [`traits`] associated with them,
//! for which the implementations are generated using
//! [`substrait_validator_derive`]. The purpose of these traits is to add basic
//! introspection capabilities to the prost structures. One of the use cases
//! for this is to let the parsing code automatically detect when the
//! validation code ignored a subtree while validating, which implies that the
//! validator hasn't checked everything and thus should not warrant that the
//! received plan is valid.

use crate::input::traits;
use crate::output::primitive_data;

use heck::ToUpperCamelCase;

#[allow(
    clippy::large_enum_variant,
    clippy::derive_partial_eq_without_eq,
    clippy::doc_lazy_continuation
)] // caused by generated code
pub mod substrait {
    // The core `substrait` and `substrait.extensions` packages come from the
    // pre-generated substrait-prost crate. The glob re-export makes the types
    // (and the nested `extensions`/`expression`/`r#type`/... submodules)
    // available under the same paths the rest of the validator already uses.
    pub use ::substrait_prost::*;

    // The validator-specific `substrait.validator` package is not provided by
    // substrait-prost, so it is still generated locally with the ProtoMeta
    // derive (see build.rs). substrait-prost exposes no `validator` module, so
    // there is no conflict with the glob re-export above.
    pub mod validator {
        include!(concat!(env!("OUT_DIR"), "/substrait.validator.rs"));
    }
}

/// Introspection trait impls (`InputNode`/`ProtoMessage`/`ProtoOneOf`/
/// `ProtoEnum`) for the substrait-prost types, generated by build.rs from
/// substrait-prost's embedded protobuf descriptor. These mirror what the
/// `ProtoMeta` derive produces for the locally-generated validator types.
// `clippy::all` because this is generated code that intentionally mirrors the
// ProtoMeta derive's output (e.g. `&self.field.as_ref()` borrows); `deprecated`
// because the emitted `proto_enum_from_i32` calls prost's deprecated `from_i32`.
#[allow(deprecated, clippy::all)]
mod substrait_prost_meta {
    include!(concat!(env!("OUT_DIR"), "/substrait_prost_meta.rs"));
}

/// Converts a Rust module path and name (the latter already processed by
/// cook_ident()) to a protobuf type path.
pub fn cook_path(module_path: &str, type_name: &str) -> String {
    let mut iter = module_path
        .split("::")
        .skip(module_path!().split("::").count())
        .map(cook_ident)
        .chain(::std::iter::once(type_name))
        .peekable();
    let mut items = vec![];
    if matches!(iter.peek(), Some(&"substrait")) {
        items.push(iter.next().unwrap().to_string());
        if matches!(iter.peek(), Some(&"extensions") | Some(&"validator")) {
            items.push(iter.next().unwrap().to_string());
        }
    }
    items.extend(iter.map(|x| x.to_upper_camel_case()));
    ::itertools::Itertools::intersperse(items.iter().map(|x| x.as_ref()), ".").collect()
}

/// Converts a Rust identifier string generated via stringify!() to the
/// original identifier by "cooking" raw identifiers.
pub fn cook_ident(ident: &str) -> &str {
    if let Some((_, keyword)) = ident.split_once('#') {
        keyword
    } else {
        ident
    }
}

impl traits::ProtoPrimitive for bool {
    fn proto_primitive_type() -> &'static str {
        "bool"
    }

    fn proto_primitive_default() -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Bool(false)
    }

    fn proto_primitive_data(&self) -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Bool(*self)
    }

    fn proto_primitive_is_default(&self) -> bool {
        !*self
    }
}

impl traits::ProtoPrimitive for u32 {
    fn proto_primitive_type() -> &'static str {
        "uint32"
    }

    fn proto_primitive_default() -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Unsigned(0)
    }

    fn proto_primitive_data(&self) -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Unsigned((*self).into())
    }

    fn proto_primitive_is_default(&self) -> bool {
        *self == 0
    }
}

impl traits::ProtoPrimitive for u64 {
    fn proto_primitive_type() -> &'static str {
        "uint64"
    }

    fn proto_primitive_default() -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Unsigned(0)
    }

    fn proto_primitive_data(&self) -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Unsigned(*self)
    }

    fn proto_primitive_is_default(&self) -> bool {
        *self == 0
    }
}

impl traits::ProtoPrimitive for i32 {
    fn proto_primitive_type() -> &'static str {
        "int32"
    }

    fn proto_primitive_default() -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Signed(0)
    }

    fn proto_primitive_data(&self) -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Signed((*self).into())
    }

    fn proto_primitive_is_default(&self) -> bool {
        *self == 0
    }
}

impl traits::ProtoPrimitive for i64 {
    fn proto_primitive_type() -> &'static str {
        "int64"
    }

    fn proto_primitive_default() -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Signed(0)
    }

    fn proto_primitive_data(&self) -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Signed(*self)
    }

    fn proto_primitive_is_default(&self) -> bool {
        *self == 0
    }
}

impl traits::ProtoPrimitive for f32 {
    fn proto_primitive_type() -> &'static str {
        "float"
    }

    fn proto_primitive_default() -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Float(0.0)
    }

    fn proto_primitive_data(&self) -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Float((*self).into())
    }

    fn proto_primitive_is_default(&self) -> bool {
        *self == 0.0
    }
}

impl traits::ProtoPrimitive for f64 {
    fn proto_primitive_type() -> &'static str {
        "double"
    }

    fn proto_primitive_default() -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Float(0.0)
    }

    fn proto_primitive_data(&self) -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Float(*self)
    }

    fn proto_primitive_is_default(&self) -> bool {
        *self == 0.0
    }
}

impl traits::ProtoPrimitive for String {
    fn proto_primitive_type() -> &'static str {
        "string"
    }

    fn proto_primitive_default() -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::String(String::new())
    }

    fn proto_primitive_data(&self) -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::String(self.clone())
    }

    fn proto_primitive_is_default(&self) -> bool {
        self.is_empty()
    }
}

impl traits::ProtoPrimitive for Vec<u8> {
    fn proto_primitive_type() -> &'static str {
        "bytes"
    }

    fn proto_primitive_default() -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Bytes(vec![])
    }

    fn proto_primitive_data(&self) -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Bytes(self.clone())
    }

    fn proto_primitive_is_default(&self) -> bool {
        self.is_empty()
    }
}

impl traits::ProtoPrimitive for prost_types::Any {
    fn proto_primitive_type() -> &'static str {
        "any"
    }

    fn proto_primitive_default() -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Any(prost_types::Any::default())
    }

    fn proto_primitive_data(&self) -> primitive_data::PrimitiveData {
        primitive_data::PrimitiveData::Any(self.clone())
    }

    fn proto_primitive_is_default(&self) -> bool {
        self.type_url.is_empty()
    }
}

#[cfg(test)]
mod prost_meta_tests {
    //! Regression tests for the introspection trait impls generated by
    //! build.rs from substrait-prost's protobuf descriptor. These pin the
    //! descriptor-derived naming (Rust module paths, protobuf type-name
    //! strings, enum variants, oneof variants) so that prost code-generation
    //! drift in a future substrait-prost release is caught here rather than as
    //! a confusing behavioral change. The boxing decisions are guarded by the
    //! compiler (a wrong choice fails to compile the generated file).

    use super::substrait;
    use crate::input::traits::{ProtoEnum, ProtoMessage, ProtoOneOf};

    #[test]
    fn nested_message_type_names() {
        // Nested-message module naming with a Rust-keyword segment (`r#type`).
        assert_eq!(
            substrait::r#type::List::proto_message_type(),
            "substrait.Type.List"
        );
        // Top-level message in the core package.
        assert_eq!(substrait::Rel::proto_message_type(), "substrait.Rel");
        // The `substrait.extensions` package maps to a separate module, and the
        // `URN` acronym must keep its original casing in the protobuf name even
        // though the Rust type is `SimpleExtensionUrn`.
        assert_eq!(
            substrait::extensions::SimpleExtensionUrn::proto_message_type(),
            "substrait.extensions.SimpleExtensionURN"
        );
    }

    #[test]
    fn nested_enum() {
        assert_eq!(
            substrait::sort_field::SortDirection::proto_enum_type(),
            "substrait.SortField.SortDirection"
        );
        assert_eq!(
            substrait::sort_field::SortDirection::proto_enum_default_variant(),
            "SORT_DIRECTION_UNSPECIFIED"
        );
        // Multi-word variant: the enum-name prefix is stripped to form the Rust
        // ident, but the protobuf value name is reported in full.
        assert_eq!(
            substrait::sort_field::SortDirection::AscNullsFirst.proto_enum_variant(),
            "SORT_DIRECTION_ASC_NULLS_FIRST"
        );
        assert_eq!(
            substrait::sort_field::SortDirection::proto_enum_from_i32(1),
            Some(substrait::sort_field::SortDirection::AscNullsFirst)
        );
    }

    #[test]
    fn oneof_with_mixed_boxing() {
        // `rel::RelType` has both boxed (`Read(Box<ReadRel>)`) and unboxed
        // (`Set(SetRel)`) variants; both must report their member field name.
        let read = substrait::rel::RelType::Read(Box::default());
        assert_eq!(read.proto_oneof_variant(), "read");
        let set = substrait::rel::RelType::Set(substrait::SetRel::default());
        assert_eq!(set.proto_oneof_variant(), "set");
    }
}
