// SPDX-License-Identifier: Apache-2.0

//! Procedural macro crate for `substrait-validator-core`.
//!
//! Provides the `#[derive(ProtoMeta)]` macro, which generates trait impls for
//! prost-generated types. The referenced traits (`ProtoMessage`, `ProtoOneOf`,
//! `ProtoEnum`, `InputNode`) live in the consuming `substrait-validator-core`
//! crate, so they are named in plain code spans rather than intra-doc links
//! here (this crate can't resolve them).
//!
//! - **Messages** (structs): `ProtoMessage`, `prost_reflect::ReflectMessage`,
//!   and `InputNode`. Type names come from `prost::Name` (generated by
//!   `prost_build::Config::enable_type_names()`); field enumeration and unknown
//!   field detection use the embedded file descriptor set via `prost-reflect`.
//!
//! - **Oneofs** (enums with single-tuple variants): `ProtoOneOf` and
//!   `InputNode`. Variant-to-field-name mapping uses `heck::ToSnakeCase` on
//!   the Rust variant identifier.
//!
//! - **Enums** (unit-variant enums): `ProtoEnum`. Type and variant names come
//!   from the descriptor pool via `cook_path` as a bootstrap key, since
//!   `prost-build` does not generate `prost::Name` impls for enums.

extern crate proc_macro;

use heck::ToSnakeCase;
use proc_macro::TokenStream;
use quote::quote;

#[doc(hidden)]
#[proc_macro_derive(ProtoMeta, attributes(proto_meta))]
pub fn proto_meta(input: TokenStream) -> TokenStream {
    proto_meta_derive(syn::parse_macro_input!(input))
}

fn proto_meta_derive(ast: syn::DeriveInput) -> TokenStream {
    match ast.data {
        syn::Data::Struct(_) => proto_meta_derive_message(&ast),
        syn::Data::Enum(ref enum_data) => match enum_data.variants.iter().next().unwrap().fields {
            syn::Fields::Unit => {
                for variant in enum_data.variants.iter() {
                    if !matches!(variant.fields, syn::Fields::Unit) {
                        panic!("all variants of a protobuf oneof enum must have a single, unnamed field");
                    }
                }

                proto_meta_derive_enum(&ast, enum_data)
            }
            syn::Fields::Unnamed(..) => {
                for variant in enum_data.variants.iter() {
                    if let syn::Fields::Unnamed(fields) = &variant.fields {
                        if fields.unnamed.len() != 1 {
                            panic!("all variants of a protobuf oneof enum must have a single, unnamed field");
                        }
                    } else {
                        panic!("all variants of a protobuf oneof enum must have a single, unnamed field");
                    }
                }

                proto_meta_derive_oneof(&ast, enum_data)
            }
            _ => panic!("enum with named elements don't map to protobuf constructs"),
        },
        syn::Data::Union(_) => panic!("unions don't map to protobuf constructs"),
    }
}

fn proto_meta_derive_message(ast: &syn::DeriveInput) -> TokenStream {
    let name = &ast.ident;
    let (impl_generics, ty_generics, where_clause) = ast.generics.split_for_impl();

    quote!(
        impl #impl_generics crate::input::traits::ProtoMessage for #name #ty_generics #where_clause {
            fn proto_message_type() -> &'static str {
                use ::once_cell::sync::Lazy;
                static TYPE_NAME: Lazy<::std::string::String> = Lazy::new(|| {
                    <#name as ::prost::Name>::full_name()
                });
                &TYPE_NAME
            }
        }

        impl #impl_generics ::prost_reflect::ReflectMessage for #name #ty_generics #where_clause {
            fn descriptor(&self) -> ::prost_reflect::MessageDescriptor {
                use ::once_cell::sync::Lazy;
                static DESC: Lazy<::prost_reflect::MessageDescriptor> = Lazy::new(|| {
                    let type_name =
                        <#name as crate::input::traits::ProtoMessage>::proto_message_type();
                    crate::input::proto::DESCRIPTOR_POOL
                        .get_message_by_name(type_name)
                        .unwrap_or_else(|| panic!("message {type_name} not in descriptor pool"))
                });
                DESC.clone()
            }
        }

        impl #impl_generics crate::input::traits::InputNode for #name #ty_generics #where_clause {
            fn type_to_node() -> crate::output::tree::Node {
                crate::output::tree::NodeType::ProtoMessage(
                    <#name as ::prost::Name>::full_name()
                ).into()
            }

            fn data_to_node(&self) -> crate::output::tree::Node {
                crate::output::tree::NodeType::ProtoMessage(
                    <#name as ::prost::Name>::full_name()
                ).into()
            }

            fn oneof_variant(&self) -> Option<&'static str> {
                None
            }

            fn parse_unknown(
                &self,
                y: &mut crate::parse::context::Context<'_>,
            ) -> bool {
                crate::parse::traversal::parse_proto_message_unknown(self, y)
            }
        }
    )
    .into()
}

fn proto_meta_derive_oneof(ast: &syn::DeriveInput, data: &syn::DataEnum) -> TokenStream {
    let name = &ast.ident;
    let (impl_generics, ty_generics, where_clause) = ast.generics.split_for_impl();

    let variant_matches: Vec<_> = data
        .variants
        .iter()
        .map(|variant| {
            let ident = &variant.ident;
            let proto_name = ident.to_string().to_snake_case();
            quote! { #name::#ident (_) => #proto_name }
        })
        .collect();

    let node_matches: Vec<_> = data
        .variants
        .iter()
        .map(|variant| {
            let ident = &variant.ident;
            quote! { #name::#ident (x) => x.data_to_node() }
        })
        .collect();

    let parse_unknown_matches: Vec<_> = data
        .variants
        .iter()
        .map(|variant| {
            let ident = &variant.ident;
            quote! { #name::#ident (x) => x.parse_unknown(y) }
        })
        .collect();

    quote!(
        impl #impl_generics crate::input::traits::ProtoOneOf for #name #ty_generics #where_clause {
            fn proto_oneof_variant(&self) -> &'static str {
                match self {
                    #(#variant_matches),*
                }
            }
        }

        impl #impl_generics crate::input::traits::InputNode for #name #ty_generics #where_clause {
            fn type_to_node() -> crate::output::tree::Node {
                crate::output::tree::NodeType::ProtoMissingOneOf.into()
            }

            fn data_to_node(&self) -> crate::output::tree::Node {
                match self {
                    #(#node_matches),*
                }
            }

            fn oneof_variant(&self) -> Option<&'static str> {
                use crate::input::traits::ProtoOneOf;
                Some(self.proto_oneof_variant())
            }

            fn parse_unknown(
                &self,
                y: &mut crate::parse::context::Context<'_>,
            ) -> bool {
                match self {
                    #(#parse_unknown_matches),*
                }
            }
        }
    )
    .into()
}

fn proto_meta_derive_enum(ast: &syn::DeriveInput, data: &syn::DataEnum) -> TokenStream {
    let name = &ast.ident;
    let name_str = name.to_string();
    let (impl_generics, ty_generics, where_clause) = ast.generics.split_for_impl();

    // Build a match from i32 discriminant to variant, used to look up
    // descriptor values by number at runtime.
    let i32_to_variant: Vec<_> = data
        .variants
        .iter()
        .map(|variant| {
            let ident = &variant.ident;
            quote! { #name::#ident => #name::#ident as i32 }
        })
        .collect();

    quote!(
        impl #impl_generics crate::input::traits::ProtoEnum for #name #ty_generics #where_clause {
            fn proto_enum_type() -> &'static str {
                use ::once_cell::sync::Lazy;
                static TYPE_NAME: Lazy<::std::string::String> = Lazy::new(|| {
                    let cook_name = crate::input::proto::cook_path(module_path!(), #name_str);
                    crate::input::proto::DESCRIPTOR_POOL
                        .get_enum_by_name(&cook_name)
                        .unwrap_or_else(|| panic!("enum {cook_name} not found in descriptor pool"))
                        .full_name()
                        .to_string()
                });
                &TYPE_NAME
            }

            fn proto_enum_default_variant() -> &'static str {
                use ::once_cell::sync::Lazy;
                static DEFAULT: Lazy<&'static str> = Lazy::new(|| {
                    let type_name = <#name as crate::input::traits::ProtoEnum>::proto_enum_type();
                    let s = crate::input::proto::DESCRIPTOR_POOL
                        .get_enum_by_name(type_name)
                        .unwrap_or_else(|| panic!("enum {type_name} not found in descriptor pool"))
                        .default_value()
                        .name()
                        .to_string();
                    ::std::boxed::Box::leak(s.into_boxed_str())
                });
                *DEFAULT
            }

            fn proto_enum_variant(&self) -> &'static str {
                use ::once_cell::sync::Lazy;
                static VARIANTS: Lazy<::std::collections::HashMap<i32, &'static str>> =
                    Lazy::new(|| {
                        let type_name =
                            <#name as crate::input::traits::ProtoEnum>::proto_enum_type();
                        crate::input::proto::DESCRIPTOR_POOL
                            .get_enum_by_name(type_name)
                            .unwrap_or_else(|| {
                                panic!("enum {type_name} not found in descriptor pool")
                            })
                            .values()
                            .map(|v| {
                                let s = ::std::boxed::Box::leak(
                                    v.name().to_string().into_boxed_str(),
                                );
                                (v.number(), s as &'static str)
                            })
                            .collect()
                    });
                let number = match self { #(#i32_to_variant),* };
                VARIANTS[&number]
            }

            fn proto_enum_from_i32(x: i32) -> Option<Self> {
                Self::from_i32(x)
            }
        }
    )
    .into()
}
