// SPDX-License-Identifier: Apache-2.0

use std::collections::HashSet;
use std::env;
use std::ffi::{OsStr, OsString};
use std::fs;
use std::io::{BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::process::Command;
use substrait_validator_build::{find_proto_files, SubstraitSync};
use walkdir::WalkDir;

/// Finds all Python files in a directory
fn find_python_files(path: &Path) -> Vec<PathBuf> {
    WalkDir::new(path)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path().extension() == Some(OsStr::new("py")) && e.metadata().unwrap().is_file()
        })
        .map(|e| e.into_path())
        .collect()
}

/// Runs protoc to generate Python files from proto files
fn run_protoc(
    protoc_path: &Path,
    input_paths: &[PathBuf],
    proto_files: &[PathBuf],
    output_path: &Path,
) -> Result<(), String> {
    let mut cmd = Command::new(protoc_path);

    for input_path in input_paths.iter() {
        let mut proto_path_arg = OsString::new();
        proto_path_arg.push("--proto_path=");
        proto_path_arg.push(input_path);
        cmd.arg(proto_path_arg);
    }

    let mut python_out_arg = OsString::new();
    python_out_arg.push("--python_out=");
    python_out_arg.push(output_path);
    cmd.arg(python_out_arg);
    cmd.args(proto_files.iter());

    let output = cmd.output().expect("failed to run protoc");
    if !output.status.success() {
        eprintln!("cmd: {:?}", cmd.get_program());
        for arg in cmd.get_args() {
            eprintln!("arg: {:?}", arg);
        }
        return Err(format!("{:?}", output));
    }

    Ok(())
}

/// Patches Python import statements in generated protobuf files
fn patch_python_imports(
    intermediate_path: &Path,
    output_path: &Path,
    python_prefix: &str,
) -> std::io::Result<()> {
    let intermediate_files = find_python_files(intermediate_path);
    let mut output_dirs = HashSet::new();

    for intermediate_file in intermediate_files {
        // Determine the output filename.
        let output_file = output_path.join(
            intermediate_file
                .strip_prefix(intermediate_path)
                .expect("intermediate file is not based in the expected directory"),
        );

        // Ensure that the directory exists, and create an __init__.py for it
        // if we haven't already.
        let mut path = output_file.to_path_buf();
        path.pop();
        if output_dirs.insert(path.clone()) {
            fs::create_dir_all(&path)?;
            path.push("__init__.py");
            fs::File::create(path)?;
        }

        // Copy and patch the file.
        let intermediate = fs::File::open(&intermediate_file)?;
        let mut output = fs::File::create(&output_file)?;
        for line in BufReader::new(intermediate).lines() {
            let line = line?;
            let line = if line.starts_with("from ") && !line.starts_with("from google") {
                format!("from {}{}", python_prefix, &line[5..])
            } else {
                line
            };
            writeln!(output, "{}", line)?;
        }
    }

    Ok(())
}

fn main() {
    // Determine the directory of Cargo.toml for this crate.
    let manifest_dir =
        PathBuf::from(&env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));

    // Create the sync configuration to determine if we're building from git
    let sync = SubstraitSync::new(manifest_dir.clone(), "proto");

    // Directory that the proto files are stored in. Check if we're in a git
    // repository with submodules (in-tree build) or building from an sdist
    // package (out-of-tree build).
    let input_paths = if sync.is_git_build() {
        vec!["../proto", "../substrait/proto"]
    } else {
        // Fallback to local proto directory (e.g., when building from extracted sdist)
        vec!["proto"]
    };

    // Ensure above path is relative to the Cargo.toml directory.
    let input_paths: Vec<PathBuf> = input_paths
        .iter()
        .map(|p| manifest_dir.join(p))
        .map(|p| dunce::canonicalize(p).unwrap())
        .collect();

    // Output directory for protoc. This is a temporary directory: it will be
    // completely deleted and then reconstructed. Afterward, the build script
    // will patch the files in here and then move them to python_out.
    let workdir = std::env::current_dir().unwrap();
    let intermediate_path = workdir.join("protoc_out");
    let output_path = workdir.join("substrait_validator");

    // The Python module prefix to patch into use statements of the files
    // generated by protobuf.
    let python_prefix = "substrait_validator.";

    // Gather all .proto files.
    let proto_files: Vec<PathBuf> = input_paths
        .iter()
        .flat_map(|p| find_proto_files(p))
        .map(|p| dunce::canonicalize(p).unwrap())
        .collect();

    // Inform cargo that changes to the .proto files require a rerun.
    for path in &proto_files {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    // Clean and recreate output directory.
    fs::remove_dir_all(&intermediate_path).ok();
    fs::create_dir_all(&intermediate_path).expect("failed to create protoc output directory");

    // Determine protoc path
    let protoc_path: PathBuf;
    #[cfg(feature = "protoc")]
    {
        // Use vendored protobuf compiler if requested.
        protoc_path = substrait_validator_build::vendored_protoc();
        println!("cargo:warning=Using vendored protoc: {:?}", protoc_path);
    }
    #[cfg(not(feature = "protoc"))]
    {
        protoc_path = prost_build::protoc_from_env();
    }

    // Run protoc to generate Python files
    run_protoc(&protoc_path, &input_paths, &proto_files, &intermediate_path)
        .expect("failed to run protoc");

    // Patch Python import statements
    patch_python_imports(&intermediate_path, &output_path, python_prefix)
        .expect("failed to patch Python imports");

    // https://pyo3.github.io/pyo3/v0.17.3/building_and_distribution.html#macos
    pyo3_build_config::add_extension_module_link_args();
}
