[package]
name = "substrait-validator-c"
version = "0.0.11"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "staticlib"]
doc = false

[build-dependencies]
cbindgen = "0.27.0"

[dependencies]
substrait-validator = { path = "../rs", version = "0.0.11" }
libc = "0.2"
thiserror = "1.0"
once_cell = "1.19"
