// SPDX-License-Identifier: Apache-2.0

//! Registry of the standard `extension:io.substrait:*` extension files, bundled
//! into the validator at build time.
//!
//! Unlike the old URI-based model, a URN is an *identifier*, not a location:
//! it cannot be downloaded. To still allow plans that reference the standard
//! Substrait extensions to be validated out of the box (and offline), the YAML
//! files shipped with the Substrait submodule are embedded into the binary and
//! resolved by their URN here. Custom extensions can be resolved by registering
//! a resolver or override on the [`Config`](crate::Config).

// Generated by build.rs; defines:
//   pub static STDLIB_EXTENSIONS: &[(&str, &[u8])];
include!(concat!(env!("OUT_DIR"), "/stdlib_extension_registry.rs"));

/// Resolves a standard extension URN to the bytes of its bundled YAML file, if
/// the URN refers to one of the standard Substrait extensions.
pub fn resolve(urn: &str) -> Option<&'static [u8]> {
    STDLIB_EXTENSIONS
        .iter()
        .find(|(known, _)| *known == urn)
        .map(|(_, data)| *data)
}
